### ISSUE TITLE
Can you release the original dataset and data processing code?

### ISSUE THREAD

**Issue by lihuiliullh** [hyren/query2box#1]
Hi Ren:

May I know how you build the dataset?
Is it possible that you release the original dataset and data processing code?

**Comment by hyren** [comment]
Hi, sorry for the late reply. I have uploaded the id2entity and id2relation mappings. The edge data can be directly taken from [this repo](https://github.com/DeepGraphLearning/KnowledgeGraphEmbedding). Let me know if you have any questions.
