### ISSUE TITLE
The difference between MRR metric of one-hop path query and link prediction 

### ISSUE THREAD

**Issue by renli1024** [hyren/query2box#4]
Thanks for opening code of such a good work first! 

I notice in the paper the MRR of model on FB15k-237 is 0.295 (Table 4), and the MRR on FB15k-237 about 1p is 0.4 (Table 9). I want to know what's the difference between these two results (from my understanding they are the same structure of data so the model should reach the identical performance? )

Thanks a lot again.

**Comment by hyren** [comment]
Thanks for your interest. We evaluate queries by first averaging all the answers of a given query and then averaging over the queries. For link prediction, the protocal is to average over all the (query, answer) pairs. Check the footnote in page 9 for more details.
