### ISSUE TITLE
Some question about the implementation of "ip" "pi", and "ui"

### ISSUE THREAD

**Issue by marcos0318** [hyren/query2box#5]
Thank you for providing the implementation for query2box.

I have discovered some discrepancies between the implementation of  "ip" "pi", and "ui"  queries and what is described in the paper, mainly regarding mismatch of the number of projections in these three queries types. 

For "pi", the code is implemented like:
![image](https://user-images.githubusercontent.com/22587235/95958023-18f89f80-0e33-11eb-968b-e0513323ce28.png)
there are two projections from set 1 and one projection from set 2. 
However, according to the paper, the "pi" should be one projection from set 1 and no projection conducted for set 2.

A similar case is also found at  "pi" and "ui", in which there exist extra projections in code than what is described in the paper.

I was wondering whether there is some misunderstanding of the code or I have misinterpreted the results showed in the paper.

**Comment by marcos0318** [comment]
Oh, I was also wondering whether the query types are named according to the shape of the dependency graph but not the computational graph. If this is the case, my problem is solved, since for each "i" and "u" there are "hidden" projections conducted before the intersection and union.

**Comment by hyren** [comment]
Yes, the computation graph corresponds more closely to the names. Or in other words, in our setting, there will always be at least one relation projection for anchor entities (the leaves on the dependency/computation graph) before logical operation intersection or union.

**Comment by marcos0318** [comment]
Thank you!
