### ISSUE TITLE
trian_triples_1c.pkl, trian_triples_2c.pkl

### ISSUE THREAD

**Issue by cx51666666** [hyren/query2box#9]
Hi
Thanks for sharing the code, how I can generate files like trian_triples_1c.pkl, trian_triples_2c.pkl.
Is it possible that you release the data processing code?
Thanks！

**Comment by Bigchen8013** [comment]
I also want to know, have you figured it out? 
Thanks for sharing!

**Comment by hyren** [comment]
Hi, please find the data generation code here.
https://github.com/snap-stanford/KGReasoning/blob/main/create_queries.py

**Comment by Bigchen8013** [comment]
Thank you very much for your reply!
I would also like to consult, what papers or theories did you refer to for the generation of logical queries?
I want to use your method (Query2Box) to implement a question answering system, but when inputting a natural language question, I don't know how to generate a logical query as in your paper. Hope to get your advice, thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hyren/query2box"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月17日(星期五) 凌晨2:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hyren/query2box] trian_triples_1c.pkl, trian_triples_2c.pkl (Issue #9)





 
Hi, please find the data generation code here.
 https://github.com/snap-stanford/KGReasoning/blob/main/create_queries.py
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fffairrrry** [comment]
> 
I also want to know how to convert natural language questions into logical queries, have you figured it out?
Thanks！

**Comment by fffairrrry** [comment]
> Thank you very much for your reply! I would also like to consult, what papers or theories did you refer to for the generation of logical queries? I want to use your method (Query2Box) to implement a question answering system, but when inputting a natural language question, I don't know how to generate a logical query as in your paper. Hope to get your advice, thank you very much!
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "hyren/query2box" ***@***.***&gt;; 发送时间:&nbsp;2021年12月17日(星期五) 凌晨2:38 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [hyren/query2box] trian_triples_1c.pkl, trian_triples_2c.pkl (Issue #9) Hi, please find the data generation code here. https://github.com/snap-stanford/KGReasoning/blob/main/create_queries.py — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***&gt;

I also want to know how to convert natural language questions into logical queries, have you figured it out?
Thanks！
